name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang-version:
          - 15
    steps:
      # Setup
      - name: Install clang-${{ matrix.clang-version }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang-version }}
      - name: Set clang-${{ matrix.clang-version }} as default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-${{ matrix.clang-version }} 999
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-${{ matrix.clang-version }} 999
      - name: Install CMake/Ninja/PulseAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            libpulse-dev

      # Checkout
      - uses: actions/checkout@v3
        with:
          lfs: true

      # Code formatting
      - name: clang-format
        run: clang-format --dry-run --Werror --style=file $(find include/ -name '*.hpp') $(find src/ -name '*.cpp')

      # Fetch cached output of ./scripts/extract-sysroot.sh --board-id t210
      - name: Download and extract Jetson Nano sysroot (aarch64)
        run: |
          mkdir -p ./sysroot/jetson-t210
          wget --no-verbose --show-progress --progress=dot:mega https://jetson-crosscompile.s3.amazonaws.com/jetson-t210-sysroot.tar.gz -O jetson-t210-sysroot.tar.gz
          tar -xzpf jetson-t210-sysroot.tar.gz -C ./sysroot/jetson-t210

      # Fetch cached output of ./scripts/extract-cuda.sh
      - name: Download and extract CUDA Toolkit 10.2 (x86_64)
        run: |
          mkdir -p ./nvidia/cuda-10.2_amd64
          wget --no-verbose --show-progress --progress=dot:mega https://jetson-crosscompile.s3.amazonaws.com/cuda-10.2_amd64.tar.gz -O cuda.tar.gz
          tar -xzpf cuda.tar.gz -C ./nvidia/cuda-10.2_amd64

      # Build
      - name: Build for host (x86_64)
        run: |
          cmake --version
          make
      - name: Build for Jetson Nano (aarch64)
        run: make jetson-nano

      # Lint
      - name: clang-tidy
        run: clang-tidy -p build/host --config-file=.clang-tidy --use-color $(find src/ -name '*.cpp')

      # Test
      - name: Run tests
        run: ctest --preset host-cpu
